### ISSUE TITLE
add DEVELOP_MODE

### ISSUE THREAD

**Issue by hannikodo** [Mogara/GameHall#11]
create 'dev' folder and copy the files under 'src'.
When DEVELOP_MODE is ON, program will access the files under 'dev'.

**Comment by hannikodo** [comment]
By default, the DEVELOP_MODE is OFF, program will access code under '/src'.
To use DEVELOP_MODE, add "-D DEVELOP_MODE=ON" when cmake, in which case the program will turn to '/dev'.

**Comment by ciiiii** [comment]
### test standard:

+ live load
    + when app starts, live load after **add/modify/delete** \*.qml without restart
+ DEVELOP_MODE
    + in this mode, build project without compiling \*.qrc
    + auto load qtquick.conf only need restart app

**Comment by ciiiii** [comment]
8ffd499efbc41cea12044ff545fa470778d6f1dc
