### ISSUE TITLE
add QuickCompiler

### ISSUE THREAD

**Issue by ciiiii** [Mogara/GameHall#18]
refer to https://doc.qt.io/QtQuickCompiler/index.html

**Comment by ciiiii** [comment]
Actually, quick compiler is only supported under commercial license.

**Comment by ciiiii** [comment]
http://doc.qt.io/qt-5/qtmodules.html#value-add-modules

**Comment by begoat** [comment]
https://www.qt.io/licensing-comparison/
yes, it is.
